project:
  type: website

website:
  title: "cousin-doc"
  navbar:
    left:
      #- href: index.qmd
      #  text: Home
      - about.qmd
      - text: "Smart COUSIN"
        menu:
        - href: smart-cousin.qmd
          text: Architecture
        - text: Tools 
              - text: Germinate
                href: https://germinateplatform.github.io/get-germinate/
              - text: Gatekeeper
                href: https://www.gatekeeperhq.com/
        - Standards.qmd
        - Templates.qmd
      - href: data-curation.qmd
        text: "Data Curation"

      - href: use-cases.qmd
        text: "Use cases"
      - href: best-practices.qmd
        text: "Best practices"
      - news.qmd
    page-footer:
    center: "© 2025 Smart COUSIN - Germinate Platform. All rights reserved."

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



